import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { ToastContainer } from "react-toastify";
import { UserProvider } from "./contexts/UserContext";

const poppins = Poppins({
  weight: "600",
  subsets: ["latin"],
  display: "swap", 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-slate-950 text-gray-300`}
      >
        <UserProvider>
          <Header />
          {children}
          <ToastContainer position="bottom-right" autoClose={2500} />
        </UserProvider>
      </body>
    </html>
  );
}
